---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image:  chuckberry321/13-kubernetes-config_frontend
        ports:
        - name: http
          containerPort: 80
        env:
          - name: BASE_URL
            value: "http://localhost:9000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  ports:
    - name: frontend
      port: 80
      targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
